M48
; DRILL file {KiCad (6.0.11-0)} date Sunday, April 09, 2023 at 10:47:34 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-09T22:47:34-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.775Y-2.65
X4.775Y-5.175
X6.65Y-2.65
X6.65Y-5.175
T0
M30
